import static org.ligi.snackengage.Dependencies.Android
import static org.ligi.snackengage.Dependencies.Libs

apply plugin: 'com.android.library'
apply from: '../gradle/maven-publish.gradle'

android {
    namespace 'org.ligi.snackengage.rate'
    compileSdk = Android.COMPILE_SDK_VERSION

    defaultConfig {
        minSdk Android.MIN_SDK_VERSION
        targetSdk Android.TARGET_SDK_VERSION
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    lint {
        baseline file("../.ci/lint-baseline-playrate.xml")
        disable 'NewerVersionAvailable'
        disable 'GradleDependency'
        checkAllWarnings true
        warningsAsErrors true
    }

}

dependencies {
    api project(':snackengage-core')
    implementation Libs.ANNOTATION
}
